function compile_hdl_design_high_pass_filter
% compile_hdl_design_high_pass_filter compiles HDL design
% Generated by Cosimulation Wizard
savedPath = getenv('PATH');
% Restore the PATH after compilation
restorePathObj = onCleanup(@()setenv('PATH', savedPath));
% Add HDL path
setenv('PATH', ['C:\modeltech64_2020.4\win64;' getenv('PATH')])
[s, r] = system(['vsim -c -do hdlverifier_compile_design.do'],'-echo');
if (s ~= 0)
    error(message('HDLLink:CosimWizard:CompilationError',r));
end

