tclcmd = { ...
'vsimulink high_pass_filter -t 1ns -voptargs=+acc  -f parameter_high_pass_filter.cfg  -socket 58170;', ...
'add wave high_pass_filter/*;', ...
};
vsim('tclstart',tclcmd,'vsimdir','C:\modeltech64_2020.4\win64')
